version: '3.8'
services:
  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=cuong
      - MYSQL_USER=cuong
      - MYSQL_DATABASE=abc
#  docker-mysql:
#    image: mysql:8.0.23
#    restart: always
#    ports:
#      - 3307:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_USER=cuongcuong
#      - MYSQL_PASSWORD=123456aA@
#      - MYSQL_DATABASE=abc
#    volumes:
#      - mysql_data:/var/lib/mysql
#      - mysql_config:/etc/mysql/conf.d
  app:
    build:
      context: .
#    restart: always
    ports:
      - 800:8000
      - 8081:8080
    environment:
#      - SERVER_PORT=8080
#      - MYSQL_URL=jdbc:mysql://cuong:cuong@db:3308/abc
#      - SPRING_DATASOURCE_URL=jdbc:mysql://docker-mysql:3306/abc?autoReconnect=true&useSSL=false
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://db:3306/abc?useSSL=false",
           "spring.datasource.username" : "cuong",
           "spring.datasource.password" : "cuong",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    depends_on:
      - db
volumes:
  mysql_data:
  mysql_config: