#
#
#version: '2'
#services:
#  mysql:
#    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - 3308:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=S3cret
#      - MYSQL_PASSWORD=cuong
#      - MYSQL_USER=cuong
#      - MYSQL_DATABASE=abc
##  app-event:
##    image: cuongnh1227/event-user
##    ports:
##      - 8087:8087
##      - 5005:5005
##    environment:
##      PORT: 8087
##      DATASOURCE_URL: jdbc:mysql://mysql:3308/abc?autoReconnect=true&useSSL=false
##      DATASOURCE_USERNAME: cuong
##      DATASOURCE_PASSWORD: cuong
##      JWT_SECRET: bezKoderSecretKey
##      JWT_EXPIRATION_MS: 86400000
##      REDIS_HOST: redis
##      REDIS_PORT: 6379
##      KAFKA_CONSUMER_GROUP_ID: tpd-loggers
##      KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
##      KAFKA_BROKER: kafka:9092
##      TPD_MESSAGES_PER_REQUEST: 10
##    depends_on:
##      - mysql
##      - redis
##      - kafka
##  app-point:
##    image: cuongnh1227/point-play
##    ports:
##      - 8085:8085
##    environment:
##      PORT: 8085
##      DATASOURCE_URL: jdbc:mysql://mysql:3308/abc?autoReconnect=true&useSSL=false
##      DATASOURCE_USERNAME: cuong
##      DATASOURCE_PASSWORD: cuong
##      JWT_SECRET: bezKoderSecretKey
##      JWT_EXPIRATION_MS: 86400000
##      REDIS_HOST: redis
##      REDIS_PORT: 6379
##      KAFKA_CONSUMER_GROUP_ID: tpd-loggers
##      KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
##      KAFKA_BROKER: kafka:9092
##      TPD_MESSAGES_PER_REQUEST: 10
##    depends_on:
##      - mysql
##      - redis
##      - kafka
##  app-time:
##    image: cuongnh1227/time-play
##    ports:
##      - 8086:8086
##    environment:
##      PORT: 8086
##      DATASOURCE_URL: jdbc:mysql://mysql:3308/abc?autoReconnect=true&useSSL=false
##      DATASOURCE_USERNAME: cuong
##      DATASOURCE_PASSWORD: cuong
##      JWT_SECRET: bezKoderSecretKey
##      JWT_EXPIRATION_MS: 86400000
##      REDIS_HOST: redis
##      REDIS_PORT: 6379
##      KAFKA_CONSUMER_GROUP_ID: tpd-loggers
##      KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
##      KAFKA_BROKER: kafka:9092
##      TPD_MESSAGES_PER_REQUEST: 10
##    depends_on:
##      - mysql
##      - redis
##      - kafka
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
##      KAFKA_ADVERTISED_HOST_NAME: 192.168.65.141
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#  redis:
#    container_name: redis
#    image: redis
##    command: redis-server --requirepass 123456
#    ports:
#      - '6379:6379'
#    restart: always
#  redis-gui:
#      container_name: redis-gui
#      image: 'redislabs/redisinsight'
#      ports:
#        - '8001:8001'
#      depends_on:
#        - redis
#volumes:
#   mysql_data:
#   mysql_config:


version: '2'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=cuong
      - MYSQL_USER=cuong
      - MYSQL_DATABASE=abc
  zookeeper:
      image: 'bitnami/zookeeper:latest'
      ports:
        - '2181:2181'
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
      image: 'bitnami/kafka:latest'
      ports:
        - '9092:9092'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      depends_on:
        - zookeeper
  redis:
      image: redis
      ports:
        - '6379:6379'
  redis-gui:
      image: patrikx3/p3x-redis-ui:latest
      ports:
        - 7843:7843
      volumes:
        # here you can set your own /home/user/p3x-redis-ui-settings folder
        - ~/p3x-redis-ui-settings:/settings

